# Generated by Django 4.1.1 on 2022-09-26 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='astronomers',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('abrName', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='abbreviated name')),
                ('dateOfBirth', models.DateField(verbose_name='date of birth')),
                ('dateOfDeath', models.DateField(blank=True, verbose_name='date of death')),
                ('placeOfWork', models.CharField(blank=True, max_length=80, verbose_name='place of work')),
            ],
            options={
                'db_table': 'Astronomers',
            },
        ),
        migrations.CreateModel(
            name='minorPlanets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
                ('diameter', models.IntegerField(verbose_name='diameter(in km.)')),
                ('discoverer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoProject.astronomers')),
            ],
            options={
                'db_table': 'Minor Planets',
            },
        ),
    ]
