# Generated by Django 4.1.1 on 2022-09-26 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minorPlanets', '0002_alter_minorplanets_discoverer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='astronomers',
            table='Astronomer',
        ),
        migrations.AlterModelTable(
            name='minorplanets',
            table='Minor Planet',
        ),
    ]
