# Generated by Django 4.1.1 on 2022-11-06 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('minorPlanets', '0005_alter_astronomers_table_alter_minorplanets_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='favMPlanets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='minorPlanets.minorplanets')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favMPlanets',
            },
        ),
    ]
