# Generated by Django 4.1.1 on 2022-11-06 19:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('minorPlanets', '0006_favmplanets_delete_favplanets'),
    ]

    operations = [

        migrations.AddField(
            model_name='minorplanets',
            name='fave',
            field=models.ManyToManyField(related_name='planet_favorite', to=settings.AUTH_USER_MODEL),
        ),

    ]
