# Generated by Django 4.1.1 on 2022-12-13 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minorPlanets', '0009_remove_astronomers_placeofwork_astronomers_fave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='astronomers',
            name='fave',
        ),
    ]
