# Generated by Django 4.1.1 on 2022-12-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minorPlanets', '0012_astronomers_id_alter_astronomers_abrname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='astronomers',
            name='id',
        ),
        migrations.AlterField(
            model_name='astronomers',
            name='abrName',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='abbreviated name'),
        ),
    ]
