# Generated by Django 4.1.1 on 2022-12-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minorPlanets', '0013_remove_astronomers_id_alter_astronomers_abrname'),
    ]

    operations = [
        migrations.AddField(
            model_name='astronomers',
            name='id',
            field=models.IntegerField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='astronomers',
            name='abrName',
            field=models.CharField(max_length=30, verbose_name='abbreviated name'),
        ),
    ]
