# Generated by Django 4.1.1 on 2022-12-13 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minorPlanets', '0014_astronomers_id_alter_astronomers_abrname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='astronomers',
            name='fave',
        ),
    ]
