# Generated by Django 4.1.1 on 2022-12-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minorPlanets', '0016_astronomers_fave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minorplanets',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
