# Generated by Django 4.1.1 on 2022-12-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minorPlanets', '0017_alter_minorplanets_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minorplanets',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
