"""users 3

Revision ID: 0278114524aa
Revises: 7d602ff8f063
Create Date: 2023-04-25 18:51:46.643010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0278114524aa'
down_revision = '7d602ff8f063'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thing3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstAtribute', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manytomany',
    sa.Column('thing2_id', sa.Integer(), nullable=True),
    sa.Column('thing3_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['thing2_id'], ['thing2.id'], ),
    sa.ForeignKeyConstraint(['thing3_id'], ['thing3.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manytomany')
    op.drop_table('thing3')
    # ### end Alembic commands ###
