"""first table

Revision ID: 1641481fc496
Revises: 
Create Date: 2023-03-28 23:36:16.787838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1641481fc496'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thing1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstAtribute', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thing1')
    # ### end Alembic commands ###
