"""change_user

Revision ID: 22ada00996ae
Revises: 0278114524aa
Create Date: 2023-06-10 13:29:00.002226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22ada00996ae'
down_revision = '0278114524aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('social_id', sa.String(length=64), nullable=False))
        batch_op.create_unique_constraint(None, ['social_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('social_id')

    # ### end Alembic commands ###
