"""empty message

Revision ID: 359c8a0d30a9
Revises: b96079fa794f
Create Date: 2023-06-10 22:51:03.746984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '359c8a0d30a9'
down_revision = 'b96079fa794f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_post',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_post')
    # ### end Alembic commands ###
