"""empty message

Revision ID: 40cf28ef5a28
Revises: 22ada00996ae
Create Date: 2023-06-10 22:06:26.331355

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '40cf28ef5a28'
down_revision = '22ada00996ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('social_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('password_hash', sa.String(length=150), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('social_id')
    )
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_User_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_User_joined_at'), ['joined_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_User_username'), ['username'], unique=True)

    op.create_table('Post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(length=128), nullable=True),
    sa.Column('Content', sa.String(), nullable=True),
    sa.Column('poster_name', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['poster_name'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Post_time'), ['time'], unique=False)

    op.drop_table('manytomany')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_email')
        batch_op.drop_index('ix_user_joined_at')
        batch_op.drop_index('ix_user_username')

    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('joined_at', mysql.DATETIME(), nullable=True),
    sa.Column('social_id', mysql.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_username', ['username'], unique=False)
        batch_op.create_index('ix_user_joined_at', ['joined_at'], unique=False)
        batch_op.create_index('ix_user_email', ['email'], unique=False)

    op.create_table('manytomany',
    sa.Column('thing2_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('thing3_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['thing2_id'], ['thing2.id'], name='manytomany_ibfk_1'),
    sa.ForeignKeyConstraint(['thing3_id'], ['thing3.id'], name='manytomany_ibfk_2'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('Post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Post_time'))

    op.drop_table('Post')
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_User_username'))
        batch_op.drop_index(batch_op.f('ix_User_joined_at'))
        batch_op.drop_index(batch_op.f('ix_User_email'))

    op.drop_table('User')
    # ### end Alembic commands ###
