"""empty message

Revision ID: 410f77c7dff8
Revises: 40cf28ef5a28
Create Date: 2023-06-10 22:09:30.257324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '410f77c7dff8'
down_revision = '40cf28ef5a28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('social_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('password_hash', sa.String(length=150), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('social_id')
    )
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_User_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_User_joined_at'), ['joined_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_User_username'), ['username'], unique=True)

    op.create_table('thing1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstAtribute', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thing3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstAtribute', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(length=128), nullable=True),
    sa.Column('Content', sa.String(length=1000), nullable=True),
    sa.Column('poster_name', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['poster_name'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Post_time'), ['time'], unique=False)

    op.create_table('thing2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstAtribute', sa.String(length=128), nullable=True),
    sa.Column('thingOne_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['thingOne_id'], ['thing1.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thing2')
    with op.batch_alter_table('Post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Post_time'))

    op.drop_table('Post')
    op.drop_table('thing3')
    op.drop_table('thing1')
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_User_username'))
        batch_op.drop_index(batch_op.f('ix_User_joined_at'))
        batch_op.drop_index(batch_op.f('ix_User_email'))

    op.drop_table('User')
    # ### end Alembic commands ###
