"""second table fix

Revision ID: e00a4ea6bcbc
Revises: f3d203baef39
Create Date: 2023-03-28 23:53:29.566626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e00a4ea6bcbc'
down_revision = 'f3d203baef39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thing2', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thingOne_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'thing1', ['thingOne_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thing2', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('thingOne_id')

    # ### end Alembic commands ###
