"""second table

Revision ID: f3d203baef39
Revises: 1641481fc496
Create Date: 2023-03-28 23:44:47.546546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3d203baef39'
down_revision = '1641481fc496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thing2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstAtribute', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thing2')
    # ### end Alembic commands ###
